# Technical Test - JLL Technologies

### Problem Statement : 
You are part of a team of 20 analysts who would like to give 2 hours each per week to support a philanthropic cause.We have dataset that lists 50k+ registered charities in Australia.
##### Problem is where to invest their time to generate the maximum value for society ?

###### As per the initial glance at the data, following are the key points I'm focusing:
- Charity cause (who they help, what they do)
- Impact or community need
- Operational scale or challenges
- Areas where skilled support is needed

This is an approach to clean the various data collected from ACNC website and keep only relevant information that we can use as a data source for tableau visualization. The links to the data sources are provided in the PPT.

## Data Cleaning

In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None) # Show all columns

In [2]:
#Import All necessary data 
# Replace 'your_file.xlsx' with the path to your Excel file

ais20_og = pd.read_excel('datadotgov_ais20.xlsx',sheet_name='Sheet1')
programs_og = pd.read_excel('datadotgov_ais20_programs.xlsx',sheet_name='Sheet1')
main_og = pd.read_excel('datadotgov_main.xlsx',sheet_name='Sheet1')

We are going to analyse each dataset and we will clean up the data.

In [4]:
ais20 = ais20_og  #I'm storing ais20_og to a new variable for data manipulation

In [5]:
ais20.shape # To identify the data structure

(51092, 93)

ais20 has 93 columns and 51092 records

In [6]:
ais20.isnull().sum()

abn                                                                                  0
charity name                                                                         0
registration status                                                                  0
charity website                                                                  17053
charity size                                                                         6
basic religious charity                                                              0
ais due date                                                                        14
date ais received                                                                    9
financial report date received                                                   19499
conducted activities                                                                 0
why charity did not conduct activities                                           48851
international activities details                                                 48665
international activities undertaken - transferring goods or services overseas        0
international activities undertaken - operating overseas including programs          0
other international activities                                                       0
other international activities description                                       50641
how purposes were pursued                                                         2253
staff - full time                                                                    0
staff - part time                                                                    0
staff - casual                                                                       0
total full time equivalent staff                                                     0
staff - volunteers                                                                   0
cash or accrual                                                                  23691
type of financial statement                                                      35321
report consolidated with more than one entity                                    35324
charity report has a modification                                                    0
type of report modification                                                      49488
charity has related party transactions                                           35348
charity has documented policies for related party transactions                   35349
fin report from                                                                   8563
fin report to                                                                     8563
revenue from government                                                              0
donations and bequests                                                               0
revenue from goods and services                                                      0
revenue from investments                                                             0
all other revenue                                                                    0
total revenue                                                                        0
other income                                                                         0
total gross income                                                                   0
employee expenses                                                                    0
interest expenses                                                                    0
grants and donations made for use in Australia                                       0
grants and donations made for use outside Australia                                  0
all other expenses                                                                   0
total expenses                                                                       0
net surplus/deficit                                                                  0
other comprehensive income                                                           0
total comprehensive income                                                           0
total current assets                                                                 0
non-current loans receivable                                                         0
other non-current assets                                                             0
total non-current assets                                                             0
total assets                                                                         0
total current liabilities                                                            0
non-current loans payable                                                            0
other non-current liabilities                                                        0
total non-current liabilities                                                        0
total liabilities                                                                    0
net assets/liabilities                                                               0
why did charity have to submit this financial report                             49049
submitted report - act                                                               0
submitted report - nsw                                                               0
submitted report - nt                                                                0
submitted report - qld                                                               0
submitted report - sa                                                                0
submitted report - tas                                                               0
submitted report - vic                                                               0
submitted report - wa                                                                0
incorporated association                                                             0
association number - act                                                         50533
association number - nsw                                                         45444
association number - nt                                                          50874
association number - qld                                                         48289
association number - sa                                                          49331
association number - tas                                                         50465
association number - vic                                                         46018
association number - wa                                                          48472
fundraising - act                                                                    0
fundraising number - act                                                         50695
fundraising - nsw                                                                    0
fundraising number - nsw                                                         47248
fundraising - nt                                                                     0
fundraising - qld                                                                    0
fundraising number - qld                                                         49122
fundraising - sa                                                                     0
fundraising number - sa                                                          50245
fundraising - tas                                                                    0
fundraising number - tas                                                         50481
fundraising - vic                                                                    0
fundraising number - vic                                                         49204
fundraising - wa                                                                     0
fundraising number - wa                                                          49961
fundraising - online                                                                 0
dtype: int64

Many columns have huge amount of rows that has NULLS. This needs to be carefully reviewed and if not required we can get rid of them.

Check the list of columns to identify if we have anything to exclude on the first glance keeping the goal in mind

In [7]:
#check the columns in the datasets
ais20.columns.tolist()

['abn',
 'charity name',
 'registration status',
 'charity website',
 'charity size',
 'basic religious charity',
 'ais due date',
 'date ais received',
 'financial report date received',
 'conducted activities',
 'why charity did not conduct activities',
 'international activities details',
 'international activities undertaken - transferring goods or services overseas',
 'international activities undertaken - operating overseas including programs',
 'other international activities',
 'other international activities description',
 'how purposes were pursued',
 'staff - full time',
 'staff - part time',
 'staff - casual',
 'total full time equivalent staff',
 'staff - volunteers',
 'cash or accrual',
 'type of financial statement',
 'report consolidated with more than one entity',
 'charity report has a modification',
 'type of report modification',
 'charity has related party transactions',
 'charity has documented policies for related party transactions',
 'fin report from',
 'fin report to',
 'revenue from government',
 'donations and bequests',
 'revenue from goods and services',
 'revenue from investments',
 'all other revenue',
 'total revenue',
 'other income',
 'total gross income',
 'employee expenses',
 'interest expenses',
 'grants and donations made for use in Australia',
 'grants and donations made for use outside Australia',
 'all other expenses',
 'total expenses',
 'net surplus/deficit',
 'other comprehensive income',
 'total comprehensive income',
 'total current assets',
 'non-current loans receivable',
 'other non-current assets',
 'total non-current assets',
 'total assets',
 'total current liabilities',
 'non-current loans payable',
 'other non-current liabilities',
 'total non-current liabilities',
 'total liabilities',
 'net assets/liabilities',
 'why did charity have to submit this financial report',
 'submitted report - act',
 'submitted report - nsw',
 'submitted report - nt',
 'submitted report - qld',
 'submitted report - sa',
 'submitted report - tas',
 'submitted report - vic',
 'submitted report - wa',
 'incorporated association',
 'association number - act',
 'association number - nsw',
 'association number - nt',
 'association number - qld',
 'association number - sa',
 'association number - tas',
 'association number - vic',
 'association number - wa',
 'fundraising - act',
 'fundraising number - act',
 'fundraising - nsw',
 'fundraising number - nsw',
 'fundraising - nt',
 'fundraising - qld',
 'fundraising number - qld',
 'fundraising - sa',
 'fundraising number - sa',
 'fundraising - tas',
 'fundraising number - tas',
 'fundraising - vic',
 'fundraising number - vic',
 'fundraising - wa',
 'fundraising number - wa',
 'fundraising - online']

There are few columns that we can exclude, as those doesn't align much with my focus points

In [8]:
# Drop columns containing 'temp' or 'debug' or 'fundraising' as i don't find them useful keepoing the goal in mind
ais20 = ais20.loc[:, ~ais20.columns.str.contains('submitted |association|fundraising')]

In [9]:
# Find columns with more than 70% nulls
null_cols = ais20.columns[ais20.isnull().sum() > 35000]
len(null_cols) # No.of columns with more than 70% NULLS

9

In [7]:
# Print unique values for those columns
for col in null_cols:
    print(f"\n--- Unique values in '{col}' (NaNs: {ais20[col].isnull().sum()}) ---")
    print(ais20[col].dropna().unique())

--- Unique values in 'why charity did not conduct activities' (NaNs: 48851) ---
['Yagoona Baptist Church has now closed and a Curch plant has been made under the name of Graceway Church.'
 'The operations and programs of the charity are undertaken by Save the Children Australia.'
 'Because of COVIC19 we were unable to conduct our usual activities' ...
 'Although, we became a registered charity on 15 November 2019, the operational services provided by WOW to the Cairns community was funded by Stratford Medical Centre until 30 June 2020, as we did not receive funding to operate as our own entity until 1 July 2020. From November 2019, we did fundraise for our fit-for-purpose mobile van.'
 'Planning and development is still in progress'
 'Baptist Relief Fund did not do any emergency relief work last year due to no disaster events.']

--- Unique values in 'international activities details' (NaNs: 48665) ---
['AMT receives gifts from churches and individuals and distributes these monies in the support of Christian workers.'
 'Providing the copyrights for our popular daily devotional , which is published in simple English and or translated in to local languages such As Nepalese, Pidgin, Tetun for printing and distribution to locals through Churches and schools or broadcast on local radio stations. We provided assistance with training and resources for improved best practice with local board committees of management in their responsibilities in good governance. Local fund-raising initiatives, Computers and broadcast software, funding of Capital works projects such as constructing studios, offices and transmission sites.'
 'Cultural Infusion s Living Culture program works to preserve cultural diversity in impoverished communities in Africa and Asia. We recognise that community cultural practices imbue members with a sense of identity and belonging.'
 ...
 'The Foundation pursued its charitable purposes in the last financial year by awards Roberta Sykes Scholarships and Bursaries to Indigenous Australians to study at overseas universities.'
 'we support our missionaries in Australia and other parts of the world.'
 'Supporting the missionary arm of the Baptist Union of Western Australia - Global Interaction with their overseas outreach and community services in Mozambique, Africa. Kalgoorlie Baptist Church has supported a family there for many years.']

--- Unique values in 'other international activities description' (NaNs: 50641) ---
['We enrol students from international areas.'
 'Providing Funds to a family who work overseas in Indonesia through church mission society net.'
 'Work in conjunction with New Zealand counterparts to support self advocacy activities via online resources'
 'Providing KYB study material in digital or print format.'
 'MAIN PRIORITY Our main priority is to provide safe housing for the children. If the children are provided with safe housing, food and clothing, they are less likely to be sold into the sex trade by their parents, who can t afford to care for them.'
 'Providing money to World Vision and Opportunity International for use in improving the health of people in developing countries'
 'We team up with communities who are battling serious social challenges. We listen to them and work with them to overcome the problems they identify, putting into place the solutions they design, and making progress in the direction they choose. The communities lead the way, with us by their side, and then - when they are firmly on the right path - we step aside and watch them move onwards on their own two feet. This is our Future, Together approach.'
 'Spreading the word of God to underprivileged peoples in Peru.'
 'Partnering with local churches and Christian organisations to provide education and training services'
 'We send money raised to Bible Society Australia, specifying what programs we wish to support, whether Indigenous Bible translation in Australia, or  various literacy or humanitarian projects overseas.'
 'Training of International Volunteers'
 "Phone counselling of refugees detained indefinitely on PNG and Nauru in Austrialia's offshore detention system."
 'Provision of donated and discounted technology, and technology training and webinars to charities in New Zealand'
 "Supporting of orphanages & local children within Africa, India and Nepal including the giving of Bibles, clothing, mosquito nets, payments for food, shoes and teaching and schooling materials.Supporting of local Pastors in locations around the world with prayer, encouragement, teaching and preaching materials, Bibles and Hosanna 'Morning Star' Publications DVDs, Music CDs. books, banners, bicycles and other materials from time to time.Hosanna Morning Star Internet Ministries Website and Youtube channel - Offering prayer, encouragement and teachings related to the Gospel of Christ Jesus our Lord - free of charge access to all worldwide."
 'education scholarships'
 'Provision of financial support for missionaries overseas.  All funding is given to a registered Australian Charity based in Australia.'
 'Qualified sonographers train doctors and midwives in obstetric ultrasound. This enables them to delivery basic healthcare and diagnosis to expectant mothers. Ultrasound is taught at Bumi Sehat, a refuge to provide safe delivery of babies where cost or access is prohibitive.'
 'Discipleship Training and counselling to churches.'
 'Liaise    educational programs with  other countries'
 'MWIA partners in collaborative, diverse and exploratory projects that support women’s leadership and community ownership. It supports partners in implementing joint initiatives in a manner consistent with development best practice.'
 'the International Certificate in Radiology Fundamentals (ICRF). This is a unique one-year online program aims to build capabilities in radiology and consequently improve health care delivery to patients.'
 'Financial support of missionary couple via Australian ACNC registered charity.Sending mission team of volunteers and funds for 2 weeks to volunteer with a charity in Cambodia.'
 'Raising funds to support charities operating overseas in partnership with Global Development Group (GDG), a registered NGO for International development. All funds raised are forwarded to GDG for receipting, forwarding of funds, meeting Australian governance standards (external conduct) and all matters of compliance.'
 'Supervision by volunteer ICU Fellows of trainees in overseas accredited hospitals'
 'The charity looks after overseas patients who are transferred to Sydney for urgent medical treatment.'
 'Events promoting the Australian screen industry to overseas audiences, and providing opportunities for collaboration'
 'The charity aims to organize at least one international conference on electricity generation, transmission and supply.'
 'Maintaining contact with scholarship recipients while they are overseas'
 'Donating to Australian registered charities that operate in overseas communities.'
 'Helping overseas communities or charities'
 'Donate to the charity Medicines Sans Frontier. This charity provides medical aid to war affected countries overseas.'
 'Our charity is based on assisting disadvantaged school kids with the immediate school kits for now as well as providing ongoing sanitary pads to girls, school uniforms'
 'Orthopaedic and plastic surgeries for disability refugees resides at Northern Iraq'
 'Providing online teaching to international audience'
 'A free access to our extensive website.A yearly 3-4 day Practicum on CPET with hands on experience for our attendees'
 'ACER collaborates with a range of international clients and stakeholders to provide services across all levels of education with the ultimate goal of improving learning'
 'We liaise with other women lawyers associations overseas in regard to research and industry statistics and development.'
 'virtual (online) prayer meetings'
 'Regular Leadership and Pastors conference' 'one payment fee'
 'praying and counselling members using zoom  during covid 19 to give hope especially to families that lost their love one.'
 'Providing Accreditation and Certification Services to overseas entities that deliver IWCF well control training.'
 'Financial support to two Australians serving as support staff at Hebron School in India https://hebronooty.org/'
 'NIM-FM undertakes no international activities.'
 'support sick people who need medical assistance'
 'Inline delivery of education'
 'Operating through a separate entity named Goalchator Orphan Care, who then transfer the funds overseas.'
 'Providing support to missionaries & their programs through two missions organizations, namely, Australian Christian Churches International Relief and Impact Missions International'
 'Training Leadership in PNG Christian Fellowship (PNGCF) denomination'
 'Supporting overseas programs'
 'Donating to organizations which are located within Australia who transfer goods or services overseas.'
 'Evangelism to the pygmies in the remote part of DRCongo, Making of the small bamboo house to be used as a place of worship and classroom. Baptizing those who accepted Jesus ChristChurch volunteers teaching and educating children and parents'
 'Christmas shoe box - fill up decorated shoe boxed with brand new items for different age groups'
 'Wildlife conservation through citizen science'
 'Supporting non-profit aid and global impact organisations through donations given by members of the church.'
 'Donations to assist charities in community welfare and emergency support work.'
 'Supporting Royal Australian Air Force members and dependents at located at Butterworth, Malaysia'
 'No international work has been conducted'
 'When disaster strikes, the world responds to meet the physical needs of communities and people in crisis. That’s important. But sometimes emotional and spiritual needs are the greatest. At the Billy Graham Evangelistic Association, we send teams of crisis-chaplains into areas ravaged by disaster to listen, offer direction to practical assistance, and share God’s hope to those experiencing great loss. We recruit and train the volunteer chaplains, and then call on them to deploy when the need arises, often at a moment’s notice.'
 'Providing christian literature to Indonesia'
 'Assistance in building church facilities, training of Pastors, relief aid'
 'Planting of Churches in new countries of Oceania Region yet to be penetrated'
 'working with Ministries of Health and other agencies on country level hepatitis B guidelines for testing, treatment and vaccination in adults and children'
 'As a diaspora-led organisation, AADO provides timely advice and information to the Australian Government on issues affecting the Afghan-Australian diaspora community and insights into the situation on the ground in Afghanistan as in affects women and their families.'
 "The Fund was established for the purpose of relieving distress and hardship amongdisadvantaged ex-servicemen and women in countries of the former of present (British)Commonwealth of Nationals and the yearly grant to the Royal Commonwealth Ex-Services League for their charitable purposes fulfils the Fund's objects."
 'Providing funds to scholars in Australia to carry out research at the European University Institute in Florence'
 'Identifying appropriate resources to empower and enrich communities to grow and develop'
 'Advocacy for persecuted Christians'
 'Conduct benevolent activities through collaboration agreements with carefully selected in-country partners.'
 'We provide disease modelling and allocative efficiency services as well as training around our modelling tools and methods'
 'Providing Christian theological education and restoring mission facilities'
 'We do not conduct International Operations.'
 'We operate as a charitable foundation'
 'Liaise with overseas Horticultural Therapy associations'
 'Fund development programs with our major partner Global Devt Group'
 'Provides the guidance and support to the overseas regions/communities to enable the Sisters Living in those regions/communities to live out the mission and charism of the Daughters of Our Lady of the Sacred Heart.'
 'SRB runs an annual conference open to its Australian and New Zealand-based membership.'
 'No overseas activity but portal wont allow me to say that.'
 'Charity main activity: Other educationOther main activities: Primary and secondary educationOther main activities: International activitiesOther: Improving schooling conditions in community schools in Pakistan'
 'PATH’s goal is to strengthen primary health care for all, and improved service delivery for PNG’s rural majority and urban disadvantaged. It is targeted at six Provincial Health Authorities (PHAs).  Our vision is to achieve 5% Indigenous participation on PATH, principally through mutual learnings and cross-cultural exchanges between PNG’s PHAs and ACCHOs/AMSs in Australia. The initial focus has been supporting start-up and transition arrangements. As the program matures, we will be involved in designing and implementing the Indigenous-to Indigenous components'
 'No international work'
 'Practical support to build and help maintain infrastructure.'
 'Grant-making to registered DGR item 1 organisations in Australia operating overseas.'
 'Assisting financially other charities as Mercy ships, CBM (Blind Mission)'
 'Educating Indonesian surgeons to be able to support local patientsAssisting complex craniofacial patients to be transferred to Australia for treat,emt'
 'Working with local and international partners to  facilitate access to education and training for disadvantaged people.'
 'Training health professionals from other countries allows for this specialised therapy to be available to therapists who would not otherwise be able to train in this area.'
 'Providing lunch for congregation every Sunday after church, when it is allowed within the Covid-guidelines.'
 "Story Week featured artists performing and presenting online from several countries, primarily for Australian audiences.'Australian Poetry Slam - Youth' worked online with young people in Mumbai, India to help them to perform their own poems and stories."
 'Providing Material Aid to Orphans'
 'Advancement of their education in their everyday life'
 'Income support and maintenance' 'Genealogy activities in Australia'
 'Communication and outreach; underwater photography and filming; scientific research; school ocean literacy support.'
 'Providing volunteer design and development advisory services to the project in Cambodia when required.'
 'Supporting overseas missionaries in their work'
 'Preparation and publication of the international academic journal The Journal of Pacific History'
 'Collaborative Clinical Trial Research'
 'With a grant provided by the Australian Government (ARENA),  the charity represents Austrlalia at the IEA Hydrogen TCP.  This includes attending all executive committee meetings and events, and taking part in international collaborative activies in hydrogen energy.'
 'Online support through access to education and public oral health related information.'
 'Hearts for Africa (Amani) Fund does not directly operate overseas development, but provide funding for J783, an overseas development project of Global Development Group.'
 'Provide mentoring, encouragement, and moral support to the church leaders and ministers of religion.'
 'Online activities with various partners in the program'
 'Online theological education based in Perth at no fee to students'
 'We mentor students who are based overseas during the Google Summer of Code program. We send a small stipend to mentors who are based overseas as a reward for their mentoring.'
 'Curating performances of Australian artists in Latin American festivals and other events and organising residences for them'
 'Religious Activities'
 'Primary & secondary education as well as housing services and food.'
 'Creating and nurturing a network of international arts dialogue and cultural development.'
 'Limited Financial Assistance' 'Supply of Bibles'
 'Providing welfare to the serving members of the military services overseas'
 'Assisting in the provision of basic health care training. Providing Christian discipleship programs.'
 "Helping immigrants or new arrival as well as support overseas's projects"
 'Seminars and Conference'
 'Working with existing community based organisations to provide training to their staff and building capacity in project management, accurate financial and resource management, monitoring and reporting standards.'
 'Support for Australian family on mission work in the Philippines'
 'We are able to donate to other organisations mostly in our own locality or region and sometimes to individuals in need. For example, we donate to prison programmes as well as drug rehabilitation programmes with a percentage of our profits each month. We can and do give practical support to homeless with provision of goods and clothing, and those released from prison occasionally, who have no family support or goods.'
 "We partner with Robin's Nest Kenya - it is a separate entity based in Kenya."
 'Transferring funds to our program partners so that we can support at risk children in Nepal and Kenya with education, homes and medical attention they urgently need.'
 'Aid and Development awareness raising in Lutheran churches and Lutheran schools in Australia.'
 'Training, research & advocacy - through social media, publishing statements, & presentation of papers at conferences.'
 'The college runs the same programs in both Australia and New Zealand, New Zealand branch is registered with NZ charity register and NZ branch accounts is lodged with NZ Charity register.  We lodge audited consolidated financial with ACNC each year.'
 'voluntourism trips with volunteers'
 'Research projects undertaken with international higher education institutions, government departments, and commercial entities.'
 'The Centre helps and counsels seafarers that have come to the ports located in Dampier & Wickham in times of crisis or in cases of injustice and, by linking with parish clergy, extends support to their families.'
 'Support for other Australian charity operating overseas.'
 'Our current international activity is via online programs only.'
 "This charity provides 2 scholarships each year for deserving students of Crete to undertake tertiary education.  It also provides a yearly donation to the Bishop of Spili's Fund."
 'provide support for those in need'
 'The SugarByHalf Education Program, developed for Australia, has been adapted to align with the New Zealand curriculum by Cool Australia, and is delivered through their website.'
 'Provision of funds for child sponsorship through World Vision. The Trust currently supports 16 children through World Vision Australia.'
 'The Charity currently does not run international operations'
 'We deliver mathematical and algorithmic/informatics competitions/enrichment programs to participating schools like the Australian Mathematics Competition or the Computational and Algorithmic Thinking competition.'
 'Online website. No other overseas activities.'
 'Prisoners visitations & medication relief'
 'provides a basic english literacy program via a web site https://www.soundandspell.org'
 'Support for deliver of overseas programs such as volunteer work'
 'Sponsoring visits to Israel by selected senior journalists, politicians and student leaders etc.'
 'Training programs/modules via online modules'
 'https://www.hha.net.au/toursTours of Historic Houses & Gardens'
 'Collecting funds in Australia for overseas aid organisation (GDG) to operate overseas project 1747 in Uganda.'

In [10]:
#I'm excluding columns with large text description here as it's difficult to read and understand from here.
ExCol = ['why charity did not conduct activities','international activities details','other international activities description']
null_cols = [col for col in null_cols if col not in ExCol]

In [9]:
for col in null_cols:
    print(f"\n--- Unique values in '{col}' (NaNs: {ais20[col].isnull().sum()}) ---")
    print(ais20[col].dropna().unique())

--- Unique values in 'type of financial statement' (NaNs: 35321) ---
['General purpose financial statements'
 'Special purpose financial statements'
 'General purpose financial statements – reduced disclosure regime'
 'General purpose financial statements – simplified disclosure'
 'General purpose financial statements   reduced disclosure regime'
 'General purpose financial statements - reduced disclosure regime'
 'General purpose financial statements   simplified disclosure'
 'Special purpose financial statement'
 'General purpose financial statements - simplified disclosure']

--- Unique values in 'report consolidated with more than one entity' (NaNs: 35324) ---
['n' 'y']

--- Unique values in 'type of report modification' (NaNs: 49488) ---
['Qualified/qualification' 'Disclaimed/disclaimer' 'Adverse']

--- Unique values in 'charity has related party transactions' (NaNs: 35348) ---
['n' 'y']

--- Unique values in 'charity has documented policies for related party transactions' (NaNs: 35349) ---
['y' 'n']

--- Unique values in 'why did charity have to submit this financial report' (NaNs: 49049) ---
['My charity is an incorporated association'
 'My charity is a charitable fundraising organisation'
 'My charity is a cooperative']

Analysing the values, we can use it for in-depth analysis like Why the report fot modified? How the related party transactions and allied documents are modified and managed. But this will direct us more towards the robustness of the charity or how well established the charities are. We cannot get a direct information about the need of support from these fields.

So let's keep them away from this analysis.

In [11]:
# Drop them from the DataFrame
ais20 = ais20.drop(columns=null_cols)
ais20.shape

(51092, 54)

In [11]:
#check again the columns in the datasets
ais20.columns.tolist()

['abn',
 'charity name',
 'registration status',
 'charity website',
 'charity size',
 'basic religious charity',
 'ais due date',
 'date ais received',
 'financial report date received',
 'conducted activities',
 'why charity did not conduct activities',
 'international activities details',
 'international activities undertaken - transferring goods or services overseas',
 'international activities undertaken - operating overseas including programs',
 'other international activities',
 'other international activities description',
 'how purposes were pursued',
 'staff - full time',
 'staff - part time',
 'staff - casual',
 'total full time equivalent staff',
 'staff - volunteers',
 'cash or accrual',
 'charity report has a modification',
 'fin report from',
 'fin report to',
 'revenue from government',
 'donations and bequests',
 'revenue from goods and services',
 'revenue from investments',
 'all other revenue',
 'total revenue',
 'other income',
 'total gross income',
 'employee expenses',
 'interest expenses',
 'grants and donations made for use in Australia',
 'grants and donations made for use outside Australia',
 'all other expenses',
 'total expenses',
 'net surplus/deficit',
 'other comprehensive income',
 'total comprehensive income',
 'total current assets',
 'non-current loans receivable',
 'other non-current assets',
 'total non-current assets',
 'total assets',
 'total current liabilities',
 'non-current loans payable',
 'other non-current liabilities',
 'total non-current liabilities',
 'total liabilities',
 'net assets/liabilities']

Going through these columns and it's values, many columns are not in alignment with our goal. So I have manually picked them up and removing here.

In [12]:
# List of columns to drop
columns_to_drop = [
    'charity website',# Not relevant for our goal
    'ais due date',  # Shows report submission deadline, not relevant for impact analysis
    'date ais received',  # Tracking of when report was received; does not affect charity operations
    'financial report date received',  # Internal ACNC processing date; not useful for prioritizing support
    'charity report has a modification',  # Audit mistakes; doesn't relate to direct need or service delivery
    'charity report has a modification',  # Not really useful for our goal
]

# Drop them from ais20
ais20 = ais20.drop(columns=columns_to_drop)

In [13]:
ais20.shape

(51092, 49)

In [13]:
#check again the columns in the datasets
ais20.columns.tolist()

['abn',
 'charity name',
 'registration status',
 'charity size',
 'basic religious charity',
 'conducted activities',
 'why charity did not conduct activities',
 'international activities details',
 'international activities undertaken - transferring goods or services overseas',
 'international activities undertaken - operating overseas including programs',
 'other international activities',
 'other international activities description',
 'how purposes were pursued',
 'staff - full time',
 'staff - part time',
 'staff - casual',
 'total full time equivalent staff',
 'staff - volunteers',
 'cash or accrual',
 'fin report from',
 'fin report to',
 'revenue from government',
 'donations and bequests',
 'revenue from goods and services',
 'revenue from investments',
 'all other revenue',
 'total revenue',
 'other income',
 'total gross income',
 'employee expenses',
 'interest expenses',
 'grants and donations made for use in Australia',
 'grants and donations made for use outside Australia',
 'all other expenses',
 'total expenses',
 'net surplus/deficit',
 'other comprehensive income',
 'total comprehensive income',
 'total current assets',
 'non-current loans receivable',
 'other non-current assets',
 'total non-current assets',
 'total assets',
 'total current liabilities',
 'non-current loans payable',
 'other non-current liabilities',
 'total non-current liabilities',
 'total liabilities',
 'net assets/liabilities']

As per the ACNC Explanatory notes, charities with ABN number like '911111111xx' are reporting groups.We can use this as a filter to limit our data.

In [14]:
count = ais20['abn'].astype(str).str.startswith('911111111').sum()
print("Number of ABNs starting with '911111111':", count)
ais20.shape

Number of ABNs starting with '911111111': 62

(51092, 49)

In [15]:
#Remove records with ABN number like '911111111xx' 
ais20 = ais20[~ais20['abn'].astype(str).str.startswith('911111111')]
ais20.shape

(51030, 49)

In [16]:
# Check the registration status column

ais20['registration status'].unique()

array(['Registered', 'Voluntarily Revoked No Longer Operating',
       'Revoked Double Defaulter', 'Voluntarily Revoked Merged',
       'Voluntarily Revoked Not Entitled To Be A Charity',
       'Voluntarily Revoked Continuing But No Longer Wants To Be A Charity',
       'Revoked ABN', 'Revoked RTS', 'Revoked Registration',
       'Revoked Compliance'], dtype=object)

This shows us the unique registration status.We should be considering only those with 'Resgistered' value, as the rest are not in alignment with our goal.

In [16]:
# Check the count for only 'Registered' status
RegCharities = (ais20['registration status'] == 'Registered').sum()
print(f"Number of charities in 'Registered' status: {RegCharities}")

Number of charities in 'Registered' status: 46214

In [17]:
# Filter the data for only 'Registered' status
ais20_final = ais20[ais20['registration status'] == 'Registered']

In [18]:
ais20_final.shape

(46214, 49)

In [20]:
ais20_final.head()

,abn,charity name,registration status,charity size,basic religious charity,conducted activities,why charity did not conduct activities,international activities details,international activities undertaken - transferring goods or services overseas,international activities undertaken - operating overseas including programs,other international activities,other international activities description,how purposes were pursued,staff - full time,staff - part time,staff - casual,total full time equivalent staff,staff - volunteers,cash or accrual,fin report from,fin report to,revenue from government,donations and bequests,revenue from goods and services,revenue from investments,all other revenue,total revenue,other income,total gross income,employee expenses,interest expenses,grants and donations made for use in Australia,grants and donations made for use outside Australia,all other expenses,total expenses,net surplus/deficit,other comprehensive income,total comprehensive income,total current assets,non-current loans receivable,other non-current assets,total non-current assets,total assets,total current liabilities,non-current loans payable,other non-current liabilities,total non-current liabilities,total liabilities,net assets/liabilities
0,11000047950,Sydney Missionary & Bible College,Registered,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270
1,11000073870,Integricare Limited,Registered,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886
2,11000761571,AUSTRALIANS IN MISSION TOGETHER,Registered,Large,n,y,NaN,AMT receives gifts from churches and individua...,y,n,n,NaN,AMT served the needs of volunteer workers in c...,2,2,0,3.20,1,NaN,01/01/2020,31/12/2020,0,2537967,51715,93486,574396,3257564,0,3257564,176773,0,0,3266654,156676,3600103,-342539,0,-342539,4939229,0,3451441,3451441,8390670,593396,0,336,336,593732,7796938
3,11001233790,The Greek Orthodox Church & Community Of The H...,Registered,Medium,n,y,NaN,NaN,n,n,n,NaN,Operations of Religious activities through th...,1,0,0,1.00,50,NaN,01/07/2019,30/06/2020,15869,54722,177947,50107,52231,350876,0,350876,62755,0,0,0,234566,297321,53555,0,53555,42423,0,0,2058485,2100908,2705,0,0,325481,328186,1772722
4,11001241005,Wangarang Industries Limited,Registered,Large,n,y,NaN,NaN,n,n,n,NaN,1. Wangarang is an Australian Supported Employ...,42,123,11,105.00,0,NaN,01/07/2019,30/06/2020,2282916,9218,1978569,13493,51638,4335834,1364,4337198,3353501,2788,0,0,779912,4136201,200997,0,200997,1646148,0,2584562,2584562,4230710,1014463,0,64289,64289,1078752,3151958

In [19]:
ais20_final = ais20_final.drop(columns='registration status')

In [20]:
ais20_final.shape

(46214, 48)

### ais20 has been cleaned and many irrelevant/least relevant columns are removed and result is stored in ais20_final variable.

### Let's play around with second dataset :  programs_og

In [21]:
programs = programs_og  #I'm storing programs_og to a new variable for data manipulation

In [22]:
programs.shape # To identify the data structure

(75757, 58)

This dataset has 58 columns and 75757 rows.

In [23]:
programs.isnull().sum()

ABN                                                                     0
Charity Name                                                            0
Registration Status                                                     0
Program name                                                            9
Classification                                                          0
Children - aged 6 to under 15                                           0
Environment                                                             0
Families                                                                0
General community in Australia                                          0
Migrants, refugees or asylum seekers                                    0
Overseas communities or charities                                       0
Aboriginal and Torres Strait Islander people                            0
Adults - aged 65 and over                                               0
Early childhood - aged under 6                                          0
Females                                                                 0
Gay, lesbian, bisexual, transgender or intersex persons                 0
Males                                                                   0
People at risk of homelessness/ people experiencing homelessness        0
People with disabilities                                                0
Victims of crime (including family violence)                            0
Animals                                                                 0
Financially disadvantaged people                                        0
People in rural/regional/remote communities                             0
People with chronic illness (including terminal illness)                0
Pre/post release offenders and/or their families                        0
Veterans and/or their families                                          0
Youth - 15 to under 25                                                  0
Adults - aged 25 to under 65                                            0
Other charities                                                         0
People from a culturally and linguistically diverse background          0
Unemployed persons                                                      0
Victims of disaster                                                     0
Other                                                                   0
other description                                                   73324
Operating online                                                        0
Operating overseas                                                      0
overseas countries                                                  71391
Operating Location 1                                                 6759
Operating Location 1 lat/long                                        2923
Operating Location 2                                                63729
Operating Location 2 lat/long                                       63556
Operating Location 3                                                70553
Operating Location 3 lat/long                                       70522
Operating Location 4                                                72570
Operating Location 4 lat/long                                       72561
Operating Location 5                                                73548
Operating Location 5 lat/long                                       73544
Operating Location 6                                                74208
Operating Location 6 lat/long                                       74206
Operating Location 7                                                74639
Operating Location 7 lat/long                                       74638
Operating Location 8                                                74948
Operating Location 8 lat/long                                       74947
Operating Location 9                                                75351
Operating Location 9 lat/long                                       75350
Operating Location 10                                               75506
Operating Location 10 lat/long                                      75506
Charity weblink                                                     48717
dtype: int64

So many columns have lots of NULLS. We need to inspect and remove those if found to be irrelevant.

In [24]:
# Drop columns containing 'Operating Location' as i don't find them useful keepoing the goal in mind
programs = programs.loc[:, ~programs.columns.str.contains('Operating Location')]

In [25]:
# Find columns with more than 70% nulls
null_cols2 = programs.columns[programs.isnull().sum() > 49000]
len(null_cols2) # No.of columns with more than 70% NULLS

2

In [26]:
# Print unique values for those columns
for col in null_cols2:
    print(f"\n--- Unique values in '{col}' (NaNs: {programs[col].isnull().sum()}) ---")
    print(programs[col].dropna().unique())

--- Unique values in 'other description' (NaNs: 73324) ---
['General community in Australia' 'Adults aged 55 and over'
 'People with mental health illness' ...
 'General communities in Australia' 'Parish of All Souls Anglican Church'
 'we support our missionaries in Australia and other parts of the world.']

--- Unique values in 'overseas countries' (NaNs: 71391) ---
['Brazil;Chad;Colombia;Congo;Fiji;France;Hong Kong;India;Italy;Mexico;Nepal;Netherlands;Papua New Guinea;Philippines;Portugal;South Africa;Spain;Thailand;Timor-Leste;Uganda;United States;Venezuela, Bolivarian Republic of;Zambia'
 'Fiji;Hong Kong;Singapore;United Arab Emirates'
 'Germany;United Kingdom;United States' ...
 'Canada;New Zealand;Singapore;South Africa;United Kingdom;United States'
 'Canada;New Zealand;United Kingdom;United States;Vanuatu'
 'Benin;France;Kenya;Niger;Papua New Guinea;Portugal;Thailand']

Let's drop these for now as I don't see them adding any insight with huge NULLS in it. Also let's drop Charity weblink as it's not useful in the current context.

In [26]:
null_cols2 = list(null_cols2)
null_cols2.append('Charity weblink')
null_cols2

['other description', 'overseas countries', 'Charity weblink']

In [27]:
programs = programs.drop(columns=null_cols2)

As per the ACNC Explanatory notes, charities with ABN number like '911111111xx' are reporting groups.We can use this as a filter to limit our data.

In [28]:
count = programs['ABN'].astype(str).str.startswith('911111111').sum()
print("Number of ABNs starting with '911111111':", count)
programs.shape

Number of ABNs starting with '911111111': 202

(75757, 35)

In [29]:
#Remove records with ABN number like '911111111xx' 
programs = programs[~programs['ABN'].astype(str).str.startswith('911111111')]
programs.shape

(75555, 35)

In [30]:
# Check the count for only 'Registered' status
RegCharities = (programs['Registration Status'] == 'Registered').sum()
print(f"Number of charities in 'Registered' status: {RegCharities}")

Number of charities in 'Registered' status: 70310

In [31]:
# Filter the data for only 'Registered' status
programs = programs[programs['Registration Status'] == 'Registered']

(70310, 35)

In [32]:
programs = programs.drop(columns='Registration Status')
programs.shape

(70310, 34)

In [33]:
#check again the columns in the datasets
programs.columns.tolist()

['ABN',
 'Charity Name',
 'Program name',
 'Classification',
 'Children - aged 6 to under 15',
 'Environment',
 'Families',
 'General community in Australia',
 'Migrants, refugees or asylum seekers',
 'Overseas communities or charities',
 'Aboriginal and Torres Strait Islander people',
 'Adults - aged 65 and over',
 'Early childhood - aged under 6',
 'Females',
 'Gay, lesbian, bisexual, transgender or intersex persons',
 'Males',
 'People at risk of homelessness/ people experiencing homelessness',
 'People with disabilities',
 'Victims of crime (including family violence)',
 'Animals',
 'Financially disadvantaged people',
 'People in rural/regional/remote communities',
 'People with chronic illness (including terminal illness)',
 'Pre/post release offenders and/or their families',
 'Veterans and/or their families',
 'Youth - 15 to under 25',
 'Adults - aged 25 to under 65',
 'Other charities',
 'People from a culturally and linguistically diverse background',
 'Unemployed persons',
 'Victims of disaster',
 'Other',
 'Operating online',
 'Operating overseas']

'Children - aged 6 to under 15',
 'Environment',
 'Families',
 'General community in Australia',
 'Migrants, refugees or asylum seekers',
 'Overseas communities or charities',
 'Aboriginal and Torres Strait Islander people',
 'Adults - aged 65 and over',
 'Early childhood - aged under 6',
 'Females',
 'Gay, lesbian, bisexual, transgender or intersex persons',
 'Males',
 'People at risk of homelessness/ people experiencing homelessness',
 'People with disabilities',
 'Victims of crime (including family violence)',
 'Animals',
 'Financially disadvantaged people',
 'People in rural/regional/remote communities',
 'People with chronic illness (including terminal illness)',
 'Pre/post release offenders and/or their families',
 'Veterans and/or their families',
 'Youth - 15 to under 25',
 'Adults - aged 25 to under 65',
 'Other charities',
 'People from a culturally and linguistically diverse background',
 'Unemployed persons',
 'Victims of disaster',
 'Other',
 'other description'
 
 #### these columns are the 'Beneficiaries'. Let's transpose these columns, which will make the tableau operations easier

In [34]:
# Let's create beneficiaries dataset for each Charity
Cols_To_Transform = ['ABN',
 'Children - aged 6 to under 15',
 'Environment',
 'Families',
 'General community in Australia',
 'Migrants, refugees or asylum seekers',
 'Overseas communities or charities',
 'Aboriginal and Torres Strait Islander people',
 'Adults - aged 65 and over',
 'Early childhood - aged under 6',
 'Females',
 'Gay, lesbian, bisexual, transgender or intersex persons',
 'Males',
 'People at risk of homelessness/ people experiencing homelessness',
 'People with disabilities',
 'Victims of crime (including family violence)',
 'Animals',
 'Financially disadvantaged people',
 'People in rural/regional/remote communities',
 'People with chronic illness (including terminal illness)',
 'Pre/post release offenders and/or their families',
 'Veterans and/or their families',
 'Youth - 15 to under 25',
 'Adults - aged 25 to under 65',
 'Other charities',
 'People from a culturally and linguistically diverse background',
 'Unemployed persons',
 'Victims of disaster',
 'Other' ]

In [35]:
# Transpose the data
benef = programs[Cols_To_Transform].set_index('ABN').stack().reset_index().rename(columns={'level_1': 'Beneficiary Type', 0: 'Value'})
# Filter only rows where Value is 'Y'
benef = benef[benef['Value'] == 'Y']

In [37]:
benef = benef.drop(columns='Value')
benef.head(10)

            ABN                                   Beneficiary Type
3   11000047950                     General community in Australia
5   11000047950                  Overseas communities or charities
17  11000047950        People in rural/regional/remote communities
22  11000047950                       Adults - aged 25 to under 65
24  11000047950  People from a culturally and linguistically di...
30  11000073870                                           Families
34  11000073870       Aboriginal and Torres Strait Islander people
36  11000073870                     Early childhood - aged under 6
58  11000073870                                           Families
62  11000073870       Aboriginal and Torres Strait Islander people

Now the 'benef' variable contains dataset that has information about Charities and their respective beneficiaries.

I can remove these transformed columns now from the original 'program' set and join back 'benef' to 'program' to get the data at a single place.

In [38]:
# Remove 'ABN' from the list since that's the key field
Cols_To_Transform.remove('ABN')

# Drop the remaining columns
programs = programs.drop(columns=Cols_To_Transform, errors='ignore')

In [211]:
programs.head()

,ABN,Charity Name,Registration Status,Program name,Classification,Operating online,Operating overseas
0,11000047950,Sydney Missionary & Bible College,Registered,Sydney Missionary & Bible College,Continuing education,N,N
1,11000073870,Integricare Limited,Registered,Supported Playgroups - North,Playgroups,N,N
2,11000073870,Integricare Limited,Registered,Early Education Centres,Early childhood education,N,N
3,11000073870,Integricare Limited,Registered,Supported Playgroups - South,Playgroups,N,N
4,11000761571,AUSTRALIANS IN MISSION TOGETHER,Registered,Worldwide Mission,Christianity,N,Y

Let's JOIN the 2 'benef' and 'programs' datasets to get combined information in single place.

In [39]:
programs_final = programs.merge(benef, how='left', on='ABN')

In [40]:
programs_final.shape

(1062215, 7)

In [41]:
programs_final.head()

,ABN,Charity Name,Program name,Classification,Operating online,Operating overseas,Beneficiary Type
0,11000047950,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,General community in Australia
1,11000047950,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,Overseas communities or charities
2,11000047950,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,People in rural/regional/remote communities
3,11000047950,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,Adults - aged 25 to under 65
4,11000047950,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,People from a culturally and linguistically di...

### programs has been cleaned and many irrelevant/least relevant columns are removed and result is stored in programs_final variable.

### Let's dive into the third data set

In [78]:
main = main_og

In [79]:
main.shape

(63184, 69)

In [80]:
main.isnull().sum()

ABN                                                                 473
Charity_Legal_Name                                                  301
Other_Organisation_Names                                          57382
Address_Type                                                          0
Address_Line_1                                                     6797
Address_Line_2                                                    57853
Address_Line_3                                                    62525
Town_City                                                          6782
State                                                              6847
Postcode                                                           6710
Country                                                            7833
Charity_Website                                                   22027
Registration_Date                                                   341
Date_Organisation_Established                                      3139
Charity_Size                                                       6660
Number_of_Responsible_Persons                                         0
Financial_Year_End                                                   14
Operates_in_ACT                                                   61194
Operates_in_NSW                                                   50596
Operates_in_NT                                                    61402
Operates_in_QLD                                                   56020
Operates_in_SA                                                    59265
Operates_in_TAS                                                   61086
Operates_in_VIC                                                   53319
Operates_in_WA                                                    58218
Operating_Countries                                               58768
PBI                                                               50789
HPC                                                               60611
Preventing_or_relieving_suffering_of_animals                      62000
Advancing_Culture                                                 57590
Advancing_Education                                               50276
Advancing_Health                                                  56539
Promote_or_oppose_a_change_to_law__government_poll_or_prac        62561
Advancing_natual_environment                                      60682
Promoting_or_protecting_human_rights                              62322
Purposes_beneficial_to_ther_general_public_and_other_analogous    55891
Promoting_reconciliation__mutual_respect_and_tolerance            61633
Advancing_Religion                                                45438
Advancing_social_or_public_welfare                                49697
Advancing_security_or_safety_of_Australia_or_Australian_public    62079
Aboriginal_or_TSI                                                 48522
Adults                                                            37306
Aged_Persons                                                      39685
Children                                                          39409
Communities_Overseas                                              58114
Early_Childhood                                                   46971
Ethnic_Groups                                                     47468
Families                                                          38283
Females                                                           42698
Financially_Disadvantaged                                         45998
LGBTIQA+                                                          61364
General_Community_in_Australia                                    39176
Males                                                             43862
Migrants_Refugees_or_Asylum_Seekers                               59157
Other_Beneficiaries                                               59975
Other_Charities                                                   55853
People_at_risk_of_homelessness                                    52777
People_with_Chronic_Illness                                       54333
People_with_Disabilities                                          48731
Pre_Post_Release_Offenders                                        59193
Rural_Regional_Remote_Communities                                 47102
Unemployed_Person                                                 53004
Veterans_or_their_families                                        57050
Victims_of_crime                                                  57319
Victims_of_Disasters                                              57917
Youth                                                             36736
animals                                                           60706
environment                                                       59865
other_gender_identities                                           61297
dtype: int64

It is observed that our key column 'ABN' has NULLS, we might need to get rid of those, as those records won't be able to join back to our existing dataset.

In [81]:
main = main[main['ABN'].notna()] #Removes rows that have NULLS for key field ABN
# Drop columns containing 'Address' as i don't find them useful keepoing the goal in mind
main = main.loc[:, ~main.columns.str.contains('Address')] #Removes unnecessary address level info
#ABN was treated as float, convert to INT
main['ABN'] = main['ABN'].astype('Int64')  # Int64 handles NaN values as well
main = main.drop(columns=['Charity_Website','Charity_Legal_Name','Other_Organisation_Names'])

In [82]:
count = main['ABN'].astype(str).str.startswith('911111111').sum()
print("Number of ABNs starting with '911111111':", count)
main.shape

Number of ABNs starting with '911111111': 0

(62711, 62)

In [83]:
#Remove records with ABN number like '911111111xx' if any 
main = main[~main['ABN'].astype(str).str.startswith('911111111')]
main.shape

(62711, 62)

In [84]:
main.columns.tolist()

['ABN',
 'Town_City',
 'State',
 'Postcode',
 'Country',
 'Registration_Date',
 'Date_Organisation_Established',
 'Charity_Size',
 'Number_of_Responsible_Persons',
 'Financial_Year_End',
 'Operates_in_ACT',
 'Operates_in_NSW',
 'Operates_in_NT',
 'Operates_in_QLD',
 'Operates_in_SA',
 'Operates_in_TAS',
 'Operates_in_VIC',
 'Operates_in_WA',
 'Operating_Countries',
 'PBI',
 'HPC',
 'Preventing_or_relieving_suffering_of_animals',
 'Advancing_Culture',
 'Advancing_Education',
 'Advancing_Health',
 'Promote_or_oppose_a_change_to_law__government_poll_or_prac',
 'Advancing_natual_environment',
 'Promoting_or_protecting_human_rights',
 'Purposes_beneficial_to_ther_general_public_and_other_analogous',
 'Promoting_reconciliation__mutual_respect_and_tolerance',
 'Advancing_Religion',
 'Advancing_social_or_public_welfare',
 'Advancing_security_or_safety_of_Australia_or_Australian_public',
 'Aboriginal_or_TSI',
 'Adults',
 'Aged_Persons',
 'Children',
 'Communities_Overseas',
 'Early_Childhood',
 'Ethnic_Groups',
 'Families',
 'Females',
 'Financially_Disadvantaged',
 'LGBTIQA+',
 'General_Community_in_Australia',
 'Males',
 'Migrants_Refugees_or_Asylum_Seekers',
 'Other_Beneficiaries',
 'Other_Charities',
 'People_at_risk_of_homelessness',
 'People_with_Chronic_Illness',
 'People_with_Disabilities',
 'Pre_Post_Release_Offenders',
 'Rural_Regional_Remote_Communities',
 'Unemployed_Person',
 'Veterans_or_their_families',
 'Victims_of_crime',
 'Victims_of_Disasters',
 'Youth',
 'animals',
 'environment',
 'other_gender_identities']

In [85]:
#Transform the states to get Operating states info
States_To_Transform = [
 'ABN',  
 'Operates_in_ACT',
 'Operates_in_NSW',
 'Operates_in_NT',
 'Operates_in_QLD',
 'Operates_in_SA',
 'Operates_in_TAS',
 'Operates_in_VIC',
 'Operates_in_WA'   
]

In [86]:
# Transpose the data
OperationalState = main[States_To_Transform].set_index('ABN').stack().reset_index().rename(columns={'level_1': 'Operating State', 0: 'Value'})
# Filter only rows where Value is 'Y'
OperationalState = OperationalState[OperationalState['Value'] == 'Y']

In [87]:
# Remove 'Operates_in_' from values in the 'Operating State' column
OperationalState['Operating State'] = OperationalState['Operating State'].str.replace('Operates_in_', '', regex=False)

In [88]:
OperationalState = OperationalState.drop(columns='Value')
OperationalState.head(10)

           ABN Operating State
0  51214424410              SA
1  62601233489             ACT
2  62601233489             NSW
3  62601233489              NT
4  62601233489             QLD
5  62601233489              SA
6  62601233489             TAS
7  62601233489             VIC
8  62601233489              WA
9  18246792704             NSW

In [89]:
# Remove 'ABN' from the list since that's the key field
States_To_Transform.remove('ABN')

# Drop the remaining columns
main = main.drop(columns=States_To_Transform, errors='ignore')

In [90]:
SubTypes_To_Transform = [
 'ABN',
 'PBI',
 'HPC',
 'Preventing_or_relieving_suffering_of_animals',
 'Advancing_Culture',
 'Advancing_Education',
 'Advancing_Health',
 'Promote_or_oppose_a_change_to_law__government_poll_or_prac',
 'Advancing_natual_environment',
 'Promoting_or_protecting_human_rights',
 'Purposes_beneficial_to_ther_general_public_and_other_analogous',
 'Promoting_reconciliation__mutual_respect_and_tolerance',
 'Advancing_Religion',
 'Advancing_social_or_public_welfare',
 'Advancing_security_or_safety_of_Australia_or_Australian_public'
]

In [91]:
# Transpose the data
SubType = main[SubTypes_To_Transform].set_index('ABN').stack().reset_index().rename(columns={'level_1': 'Sub Type', 0: 'Value'})
# Filter only rows where Value is 'Y'
SubType = SubType[SubType['Value'] == 'Y']

In [92]:
SubType = SubType.drop(columns='Value')
SubType.head()

           ABN                      Sub Type
0  51214424410           Advancing_Education
1  62601233489            Advancing_Religion
2  18246792704  Advancing_natual_environment
3  64423343545            Advancing_Religion
4  28650300600           Advancing_Education

In [93]:
# Remove 'ABN' from the list since that's the key field
SubTypes_To_Transform.remove('ABN')

# Drop the remaining columns
main = main.drop(columns=SubTypes_To_Transform, errors='ignore')

In [94]:
main.columns.tolist()

['ABN',
 'Town_City',
 'State',
 'Postcode',
 'Country',
 'Registration_Date',
 'Date_Organisation_Established',
 'Charity_Size',
 'Number_of_Responsible_Persons',
 'Financial_Year_End',
 'Operating_Countries',
 'Aboriginal_or_TSI',
 'Adults',
 'Aged_Persons',
 'Children',
 'Communities_Overseas',
 'Early_Childhood',
 'Ethnic_Groups',
 'Families',
 'Females',
 'Financially_Disadvantaged',
 'LGBTIQA+',
 'General_Community_in_Australia',
 'Males',
 'Migrants_Refugees_or_Asylum_Seekers',
 'Other_Beneficiaries',
 'Other_Charities',
 'People_at_risk_of_homelessness',
 'People_with_Chronic_Illness',
 'People_with_Disabilities',
 'Pre_Post_Release_Offenders',
 'Rural_Regional_Remote_Communities',
 'Unemployed_Person',
 'Veterans_or_their_families',
 'Victims_of_crime',
 'Victims_of_Disasters',
 'Youth',
 'animals',
 'environment',
 'other_gender_identities']

In [95]:
Benef_To_Transform = [
 'ABN',
 'Aboriginal_or_TSI',
 'Adults',
 'Aged_Persons',
 'Children',
 'Communities_Overseas',
 'Early_Childhood',
 'Ethnic_Groups',
 'Families',
 'Females',
 'Financially_Disadvantaged',
 'LGBTIQA+',
 'General_Community_in_Australia',
 'Males',
 'Migrants_Refugees_or_Asylum_Seekers',
 'Other_Beneficiaries',
 'Other_Charities',
 'People_at_risk_of_homelessness',
 'People_with_Chronic_Illness',
 'People_with_Disabilities',
 'Pre_Post_Release_Offenders',
 'Rural_Regional_Remote_Communities',
 'Unemployed_Person',
 'Veterans_or_their_families',
 'Victims_of_crime',
 'Victims_of_Disasters',
 'Youth',
 'animals',
 'environment',
 'other_gender_identities'
]

In [96]:
# Transpose the data
Beneficiary = main[Benef_To_Transform].set_index('ABN').stack().reset_index().rename(columns={'level_1': 'Beneficiary', 0: 'Value'})
# Filter only rows where Value is 'Y'
Beneficiary = Beneficiary[Beneficiary['Value'] == 'Y']

In [97]:
Beneficiary = Beneficiary.drop(columns='Value')
Beneficiary.head(20)

            ABN                          Beneficiary
0   51214424410                         Aged_Persons
1   51214424410       General_Community_in_Australia
2   62601233489                              Females
3   18246792704                    Aboriginal_or_TSI
4   18246792704                               Adults
5   18246792704                         Aged_Persons
6   18246792704                             Children
7   18246792704                      Early_Childhood
8   18246792704                        Ethnic_Groups
9   18246792704                             Families
10  18246792704                              Females
11  18246792704            Financially_Disadvantaged
12  18246792704                             LGBTIQA+
13  18246792704       General_Community_in_Australia
14  18246792704                                Males
15  18246792704  Migrants_Refugees_or_Asylum_Seekers
16  18246792704             People_with_Disabilities
17  18246792704           Pre_Post_Release_Offenders
18  18246792704    Rural_Regional_Remote_Communities
19  18246792704                                Youth

Beneficiary info is already available with us in the above table(programs). So this will be a repetitive info for us while joining these 2 datasets together. So let's not keep these columns.

In [98]:
# Remove 'ABN' from the list since that's the key field
Benef_To_Transform.remove('ABN')

# Drop the remaining columns
main = main.drop(columns=Benef_To_Transform, errors='ignore')

In [100]:
main.head()
main.shape

(62711, 11)

In [101]:
# Left join 'main' with 'SubType' on 'ABN'
main_final = main.merge(SubType, on='ABN', how='left')

## Left join the result with 'Beneficiary' on 'ABN' 
#main_final = main_final.merge(Beneficiary, on='ABN', how='left') --Considered this initially, but this increases the redundancy

# Left join the result with 'OperationalState' on 'ABN'
main_final = main_final.merge(OperationalState, on='ABN', how='left')

In [110]:
main_final.shape

(109231, 13)

In [111]:
main_final.head(20)

,ABN,Town_City,State,Postcode,Country,Registration_Date,Date_Organisation_Established,Charity_Size,Number_of_Responsible_Persons,Financial_Year_End,Operating_Countries,Sub Type,Operating State
0,51214424410,Enfield,SA,5085,Australia,20/02/2018,20/02/2018,NaN,9,30-Jun,NaN,Advancing_Education,SA
1,62601233489,Briar Hill,VIC,3088,Australia,01/07/2023,09/09/2014,NaN,10,30-Jun,NaN,Advancing_Religion,ACT
2,62601233489,Briar Hill,VIC,3088,Australia,01/07/2023,09/09/2014,NaN,10,30-Jun,NaN,Advancing_Religion,NSW
3,62601233489,Briar Hill,VIC,3088,Australia,01/07/2023,09/09/2014,NaN,10,30-Jun,NaN,Advancing_Religion,NT
4,62601233489,Briar Hill,VIC,3088,Australia,01/07/2023,09/09/2014,NaN,10,30-Jun,NaN,Advancing_Religion,QLD
5,62601233489,Briar Hill,VIC,3088,Australia,01/07/2023,09/09/2014,NaN,10,30-Jun,NaN,Advancing_Religion,SA
6,62601233489,Briar Hill,VIC,3088,Australia,01/07/2023,09/09/2014,NaN,10,30-Jun,NaN,Advancing_Religion,TAS
7,62601233489,Briar Hill,VIC,3088,Australia,01/07/2023,09/09/2014,NaN,10,30-Jun,NaN,Advancing_Religion,VIC
8,62601233489,Briar Hill,VIC,3088,Australia,01/07/2023,09/09/2014,NaN,10,30-Jun,NaN,Advancing_Religion,WA
9,18246792704,Liverpool BC,NSW,1871,Australia,27/04/2017,20/11/1997,NaN,10,30-Jun,NaN,Advancing_natual_environment,NSW
10,64423343545,PARAP,NT,0820,Australia,12/05/2021,01/07/1977,Large,9,31-Dec,AUS,Advancing_Religion,NT
11,64423343545,PARAP,NT,0820,Australia,12/05/2021,01/07/1977,Large,9,31-Dec,AUS,Advancing_Religion,SA
12,64423343545,PARAP,NT,0820,Australia,12/05/2021,01/07/1977,Large,9,31-Dec,AUS,Advancing_Religion,WA
13,28650300600,St Lucia,QLD,4072,Australia,18/05/2021,18/05/2021,NaN,7,31-Dec,NaN,Advancing_Education,QLD
14,96142275848,Jurien Bay,WA,6516,Australia,30/04/2021,30/04/2021,Medium,6,30-Jun,NaN,Advancing_security_or_safety_of_Australia_or_A...,NaN
15,96996145228,NaN,NaN,NaN,NaN,27/01/2021,27/01/2021,Small,3,30-Jun,NaN,Advancing_Education,VIC
16,96996145228,NaN,NaN,NaN,NaN,27/01/2021,27/01/2021,Small,3,30-Jun,NaN,Purposes_beneficial_to_ther_general_public_and...,VIC
17,96996145228,NaN,NaN,NaN,NaN,27/01/2021,27/01/2021,Small,3,30-Jun,NaN,Advancing_social_or_public_welfare,VIC
18,92552916865,Brunswick East,VIC,3057,Australia,01/06/2021,31/05/2021,Small,4,31-Dec,AUS,Advancing_Culture,VIC
19,92552916865,Brunswick East,VIC,3057,Australia,01/06/2021,31/05/2021,Small,4,31-Dec,AUS,Advancing_Education,VIC

We have our main dataset also ready. Now we have to Join all 3 datasets and use that 'Combined' data for visualisation and further analysis

### Combining 'ais20_final','Programs_final' and 'main_final'

Since I'm focusing on data from all the 3 datasets, I'll be doing an INNER JOIN here. I'm going to continue my analysis on the Charities that are available in all the 3 datasets.

ais20_final has 'abn' as the key column name. We need to make that same for all three datsets.

In [106]:
ais20_final.rename(columns={'abn': 'ABN'}, inplace=True)

In [107]:
# Inner join 'ais20' with 'program' on 'ABN'
finaldata = ais20_final.merge(programs_final, on='ABN', how='inner')

# Inner join 'main' with 'finaldata' on 'ABN'
finaldata = finaldata.merge(main_final, on='ABN', how='inner')

finaldata.shape

(2161617, 66)

In [109]:
finaldata.shape

(2161617, 66)

In [112]:
finaldata.head(20)

,ABN,charity name,charity size,basic religious charity,conducted activities,why charity did not conduct activities,international activities details,international activities undertaken - transferring goods or services overseas,international activities undertaken - operating overseas including programs,other international activities,other international activities description,how purposes were pursued,staff - full time,staff - part time,staff - casual,total full time equivalent staff,staff - volunteers,cash or accrual,fin report from,fin report to,revenue from government,donations and bequests,revenue from goods and services,revenue from investments,all other revenue,total revenue,other income,total gross income,employee expenses,interest expenses,grants and donations made for use in Australia,grants and donations made for use outside Australia,all other expenses,total expenses,net surplus/deficit,other comprehensive income,total comprehensive income,total current assets,non-current loans receivable,other non-current assets,total non-current assets,total assets,total current liabilities,non-current loans payable,other non-current liabilities,total non-current liabilities,total liabilities,net assets/liabilities,Charity Name,Program name,Classification,Operating online,Operating overseas,Beneficiary Type,Town_City,State,Postcode,Country,Registration_Date,Date_Organisation_Established,Charity_Size,Number_of_Responsible_Persons,Financial_Year_End,Operating_Countries,Sub Type,Operating State
0,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,General community in Australia,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Education,NSW
1,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,General community in Australia,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Religion,NSW
2,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,Overseas communities or charities,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Education,NSW
3,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,Overseas communities or charities,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Religion,NSW
4,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,People in rural/regional/remote communities,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Education,NSW
5,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,People in rural/regional/remote communities,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Religion,NSW
6,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,Adults - aged 25 to under 65,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Education,NSW
7,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,Adults - aged 25 to under 65,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Religion,NSW
8,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,People from a culturally and linguistically di...,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Education,NSW
9,11000047950,Sydney Missionary & Bible College,Large,n,y,NaN,NaN,n,n,n,NaN,"Conducting an interdenominational, community b...",37,11,20,56.45,3,NaN,01/01/2020,31/12/2020,1153000,1004051,5912764,3975,1668,8075458,35452,8110910,3178458,3307,336602,0,3404370,6922737,1188173,0,1188173,3689978,0,30993759,30993759,34683737,925378,70000,82089,152089,1077467,33606270,Sydney Missionary & Bible College,Sydney Missionary & Bible College,Continuing education,N,N,People from a culturally and linguistically di...,Croydon,NSW,2132,Australia,03/12/2012,NaN,Large,9,31-Dec,NaN,Advancing_Religion,NSW
10,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Families,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Purposes_beneficial_to_ther_general_public_and...,NaN
11,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Families,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Advancing_social_or_public_welfare,NaN
12,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Aboriginal and Torres Strait Islander people,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Purposes_beneficial_to_ther_general_public_and...,NaN
13,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Aboriginal and Torres Strait Islander people,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Advancing_social_or_public_welfare,NaN
14,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Early childhood - aged under 6,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Purposes_beneficial_to_ther_general_public_and...,NaN
15,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Early childhood - aged under 6,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Advancing_social_or_public_welfare,NaN
16,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Families,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Purposes_beneficial_to_ther_general_public_and...,NaN
17,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Families,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Advancing_social_or_public_welfare,NaN
18,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Aboriginal and Torres Strait Islander people,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Purposes_beneficial_to_ther_general_public_and...,NaN
19,11000073870,Integricare Limited,Large,n,y,NaN,NaN,n,n,n,NaN,We are an early education provider and also of...,120,80,25,150.00,3,NaN,01/07/2019,30/06/2020,6271343,85250,7823475,574470,105745,14860283,2988,14863271,11251713,0,0,0,3282691,14534404,328867,0,328867,6602193,0,12546393,12546393,19148586,2568965,0,209735,209735,2778700,16369886,Integricare Limited,Supported Playgroups - North,Playgroups,N,N,Aboriginal and Torres Strait Islander people,Burwood,NSW,2134,Australia,03/12/2012,31/12/1881,Large,5,30-Jun,NaN,Advancing_social_or_public_welfare,NaN

In [311]:
print(sorted(finaldata.columns)) #Print the column names in sorted format to identify duplicate columns

['ABN', 'Beneficiary', 'Beneficiary Type', 'Charity Name', 'Charity_Legal_Name', 'Charity_Size', 'Classification', 'Country', 'Date_Organisation_Established', 'Financial_Year_End', 'Number_of_Responsible_Persons', 'Operating State', 'Operating online', 'Operating overseas', 'Operating_Countries', 'Other_Organisation_Names', 'Postcode', 'Program name', 'Registration Status', 'Registration_Date', 'State', 'Sub Type', 'Town_City', 'Value_x', 'Value_x', 'Value_y', 'Value_y', 'all other expenses', 'all other revenue', 'basic religious charity', 'cash or accrual', 'charity name', 'charity size', 'conducted activities', 'donations and bequests', 'employee expenses', 'fin report from', 'fin report to', 'grants and donations made for use in Australia', 'grants and donations made for use outside Australia', 'how purposes were pursued', 'interest expenses', 'international activities details', 'international activities undertaken - operating overseas including programs', 'international activities undertaken - transferring goods or services overseas', 'net assets/liabilities', 'net surplus/deficit', 'non-current loans payable', 'non-current loans receivable', 'other comprehensive income', 'other income', 'other international activities', 'other international activities description', 'other non-current assets', 'other non-current liabilities', 'registration status', 'revenue from goods and services', 'revenue from government', 'revenue from investments', 'staff - casual', 'staff - full time', 'staff - part time', 'staff - volunteers', 'total assets', 'total comprehensive income', 'total current assets', 'total current liabilities', 'total expenses', 'total full time equivalent staff', 'total gross income', 'total liabilities', 'total non-current assets', 'total non-current liabilities', 'total revenue', 'why charity did not conduct activities']

In [113]:
finaldata.to_csv('finaldata.csv', index=False)  # Save as CSV
# or
#finaldata.to_excel('finaldata.xlsx', index=False)  # Save as Excel

### We will use finaldata.csv as the source for our tableu operations. Let's do our further analysis over there.

I'm saving the individual files, which I can use to validate data.

In [ ]:
main_final.to_csv('main_final.csv', index=False)  # Save as CSV

In [ ]:
programs_final.to_csv('programs_final.csv', index=False)  # Save as CSV

In [21]:
ais20_final.to_csv('ais20_final.csv', index=False)  # Save as CSV

<h2 style="text-align: center;">-- End --</h2>